add/urls.py
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url

app_name='add'

urlpatterns = [
    path('', views.get_schedule, name='adds'),
    path('django/', views.get_json, name = 'json'),
]
urlpatterns += staticfiles_urlpatterns()

apptk/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='apptk'

urlpatterns = [
    path('', views.home, name='home'),
    path('signin/', views.signin, name='signin'),
    path('signup/',views.regis,name='signup'),
    path('logout/',views.logout_req,name='logout'),
    
]

urlpatterns += staticfiles_urlpatterns()

book/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='book'

urlpatterns = [
    path('', views.book, name='book'),
    path('django/', views.get_json, name = 'json'),
    
]

urlpatterns += staticfiles_urlpatterns()

history/urls.py
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='history'

urlpatterns = [
    path('', views.history, name='history'),   
]

urlpatterns += staticfiles_urlpatterns()

tk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apptk.urls')),
    path('add/', include('add.urls')),
    path('book/', include('book.urls')),
    path('history/',include('history.urls')),
]

add/models.py
from django.db import models

class daftar(models.Model):
    display_nama_tempat_parkir = models.CharField(max_length = 30)
    display_lokasi = models.CharField(max_length = 30)
    

apptk/models.py
from django.db import models
from django.contrib.auth.models import User

class mainUser(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    namaPanggil=models.CharField(max_length=30)

# Create your models here.

book/models.py
from django.db import models
from apptk.models import mainUser

def getID():
    return 1

    
class booking(models.Model):
    nama_tempat=models.CharField(max_length=100)
    lokasi=models.CharField(max_length=200)
    jam=models.CharField(max_length=5)
    milik=models.ForeignKey(mainUser,on_delete=models.CASCADE,default=getID)

history/models.py
from django.db import models

# Create your models here.

add/forms.py
from django import forms

class myForm(forms.Form):
        nama_tempat = forms.CharField(label='Nama Stasiun', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Masukkan nama Stasiun'}))
        lokasi = forms.CharField(label = 'Lokasi', max_length = 70,widget=forms.TextInput(attrs={'placeholder': 'Masukan Lokasi Tempat'}))
        
        
        

apptk/forms.py
from django import forms
from .models import mainUser
from django.contrib.auth.models import User

class formPenting(forms.ModelForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder' :'Masukan Username','id':'forms','id':'username'}))
    email=forms.CharField(widget=forms.TextInput(attrs={'placeholder' :'Masukan E-mail','class':'forms','id':'email'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder' :'Masukan Password','class':'forms','id':'password'}))
    class Meta:
        model=User
        fields=['username','email','password']

class formU(forms.ModelForm):
    namaPanggil=forms.CharField(max_length=30,label="Nama Panggilan",widget=forms.TextInput(attrs={'placeholder':'Masukkan nama panggil anda','id':'namaPanggil'}))
    class Meta:
        model=mainUser
        fields=['namaPanggil']

book/forms.py
from django import forms
from add.models import daftar

                

class bookForm(forms.Form):

        # nama_tempat = forms.CharField(label='Nama Tempat Parkir', max_length=100)
        nama_tempat=forms.CharField(label='Nama Tempat Parkir',max_length=20)
        lokasi = forms.CharField(label = 'Lokasi', max_length = 55)
        # jam=forms.CharField(label='Jam' ,widget=forms.TextInput(attrs={'placeholder': 'HH:M'}))

apptk/views.py
from django.shortcuts import render,redirect
from .forms import formU,formPenting
from .models import mainUser

from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,logout,authenticate

def home(request):
    return render(request,'hello.html')

def signin(request):
    if request.method=="POST":
        form=AuthenticationForm(request,data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username','')
            password = form.cleaned_data.get('password','')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                messages.info(request,f"Congratulations, you're login now {username}")
                return render(request,'hello.html',{"message":username})
            else:
                messages.error(request,"There is some error in username or password")

        else:
            messages.error(request,"There is some error in username or password")
    
    form=AuthenticationForm()
    return render(request,'signin.html',{"form":form})

def regis(request):
    if(request.method == "POST"):
        form=formPenting(request.POST)
        profile=formU(request.POST)
        if form.is_valid() and profile.is_valid():
            user =form.save(commit=False)
            username = form.cleaned_data.get('username','')
            email=form.cleaned_data.get('email','')
            password = form.cleaned_data.get('password','')
            print('masuk sini')
            user.set_password(password)
            user.save()
            akun=profile.save(commit=False)
            akun.user=user
            akun.save()
            return redirect("apptk:signup")
        else:
            return redirect("/")
        
    form=formU()
    formUse=formPenting()
    context={
        'formUser':formUse,
        'formAcc':form,
    }

    return render(request,'signup.html',context)

def logout_req(request):
    logout(request)
    return redirect("apptk:signin")

book/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,JsonResponse
from add.models import daftar
from .forms import bookForm
from .models import booking
from apptk.models import mainUser
import datetime
import json


def book(request):
    if request.method == 'POST':
        formB = bookForm(request.POST)
        now = datetime.datetime.now()
        if formB.is_valid():

            now = datetime.datetime.now()
            hasilBook = booking(
                                lokasi = formB.data['lokasi'],
                                jam=str(now.hour)+":"+str(now.minute),                    
                                nama_tempat = formB.data['nama_tempat'],
                                milik=mainUser.objects.get(user=request.user))

                                
            print("sukses")
            hasilBook.save()
            
        return redirect('/book/')
    else:
        formB = bookForm()
        
    return render(request, 'book.html', {'formB':formB})
    
def get_json(request):
    db=daftar.objects.all()
    data_string='{"stasiun":['
    for i in db:
        strings=str(i.display_nama_tempat_parkir)
        data_string+='{"obj":"'+strings+'"},'
        # {"code":"AKB","location":"Aekloba, Labuhan Batu"},
    
    data_string=data_string[:-1]
    data_string+="]}"
    data_json = json.dumps(data_string)
    return HttpResponse(data_json, content_type="application/json")

history/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from book.models import booking
from apptk.models import mainUser

# Create your views here.
def history(request):
	if request.user.is_authenticated:
		obj=mainUser.objects.get(user=request.user)
		daftar_parkir = {"daftar_parkir":booking.objects.filter(milik=obj)}
		return render(request,'hist.html',daftar_parkir)
	return render(request,'hist.html')

book/templates/book.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Book</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static './bootstrap-4.3.1/css/bootstrap.css' %}" type="text/css"/>
	<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'css/ini.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
	<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script type="text/javascript" src="{% static 'javascript/coba.js' %}"></script>
</head>
	<body id="main">
			<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
					<a class="navbar-brand" href="/">Parkingin</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
						<div class="navbar-nav">
							<a class="nav-item nav-link" href="{% url 'apptk:home' %}">Home <span class="sr-only">(current)</span></a>
							<a class="nav-item nav-link active" href="/book/">Book</a>
							<a class="nav-item nav-link " href="/history/">History</a>
							<a class="nav-item nav-link" href="/add/">Request Places</a>
						</div>
						<ul class = "navbar-nav mr-auto">
								{% csrf_token %}
								{% if user.is_authenticated %}
								<a class="nav-item nav-link mr-auto", href="{% url 'apptk:logout' %}">Logout</a>
								{% endif %}
						</ul>
						<label class="switch">
							<input type="checkbox" onclick="darkLight()" id="checkBox" >
							<span class="slider"></span>
						</label>
					</div>
				</nav>
		{% csrf_token %}
        {% if user.is_authenticated %}
      	{% else %}
		<a href="{% url 'apptk:signin' %}"><strong>Login</strong></a>
		<br>
		<a href="{% url 'apptk:signup' %}"><strong>Register New Account</strong></a>
      	{% endif %}
		<div class = "cek text-center">
			<form action="/book/" method="POST">
				<div class = "form-group text-center">
					{% csrf_token %}
					<p><br></p>
					{{ formB }}
				</div>
				{% csrf_token %}
        		{% if user.is_authenticated %}
				<input class="btn btn-primary" type="submit" value="Submit">
				{% endif %}
			</form>
			{% if hasil > 0 %}
			<ul class="statuss">
				{% for jawab in hasil %}
					<li>
						<p>{{jawab}}</p>
					</li>
				{% endfor %}    
			</ul>
		{% else %}
			<p>No status found.</p>
		{% endif %}
			
		</div>
		<div class = "wrapper text-center">
			<img src="{% static 'images/parkinglot.jpg' %}" class="contact img-fluid" alt="Responsive image" width = "40%">
		</div>
		<script src="{% static 'js/jquery.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>
	</body>
</html>	